language: node_js
node_js: node

cache:
  yarn: true

install:
  - (cd - &&
    git clone --depth=1 https://github.com/dmitmel/ultimate-crosscode-typedefs &&
    cd ultimate-crosscode-typedefs &&
    yarn link)
  - yarn link ultimate-crosscode-typedefs
  - yarn install

script:
  - yarn run build && yarn run lint && yarn run check-fmt

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
